#include <WiFiClientSecure.h>
#include <WiFiManager.h> // https://github.com/tzapu/WiFiManager
#include "WiFi.h"

WiFiClientSecure net = WiFiClientSecure();
String userInputTopic;


// Hardcoded wifi
// void wifiManagerSetup()
// {
//     WiFi.mode(WIFI_STA);
//     WiFi.begin("tim", "shopkeeper2");
//     Serial.println("Connecting to Wi-Fi (ensure that it's 2.4Ghz!!!");

//     while (WiFi.status() != WL_CONNECTED)
//     {
//         delay(500);
//         Serial.print(".");
//     }
// }

// "Auto" wifi
void wifiManagerSetup()
{
    WiFi.mode(WIFI_STA);
    WiFiManager wm;

    // Uncomment for wifi page setup
    wm.resetSettings();
    bool res;
    WiFiManagerParameter custom_text_box("my_text", "Enter your string here", "default string", 50);
    wm.addParameter(&custom_text_box);

    // Change what credentials of local network generated by the board
    res = wm.autoConnect("TOV_thing420", "password"); // anonymous ap

    if (!res)
    {
        Serial.println("Failed to connect");
        // ESP.restart();
    }
    else
    {
        // if you get here you have connected to the WiFi
        Serial.println("connected");
    }
    userInputTopic = custom_text_box.getValue();
}

void setup()
{
    wifiManagerSetup();
}

void loop()
{
    // put your main code here, to run repeatedly:
    Serial.println("yo");
    delay(10000);
}